go_binary(
    name = "main",
    srcs = [
        "main.go",
        ],
    deps = [
        "//third_party/go:grpc",
        "//backend/api/proto:user",
        "//backend/api/grpc/handlers",
    ]
)