// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID                int64          `json:"id"`
	FirstName         string         `json:"first_name"`
	LastName          string         `json:"last_name"`
	Username          string         `json:"username"`
	City              sql.NullString `json:"city"`
	Country           sql.NullString `json:"country"`
	Profile           sql.NullString `json:"profile"`
	ProfileMedium     sql.NullString `json:"profile_medium"`
	CreationTimestamp time.Time      `json:"creation_timestamp"`
}
